#!/usr/bin/env python3
from __future__ import annotations

import argparse
import json
import re
import subprocess
from pathlib import Path

from scriptlib import default_release_build_root, default_split_root, repo_root_from_script


WEBKIT_PATH = "/System/Library/Frameworks/WebKit.framework/WebKit"


def run(cmd: list[str]) -> str:
    p = subprocess.run(cmd, capture_output=True, text=True, check=True)
    return p.stdout


def parse_clients_from_ipsw_imports(dsc_path: Path) -> list[str]:
    text = run(["ipsw", "dyld", "imports", str(dsc_path), WEBKIT_PATH])
    clients: list[str] = []
    in_dylib_block = False
    for raw in text.splitlines():
        line = raw.strip()
        if line.startswith("In DSC (Dylibs)"):
            in_dylib_block = True
            continue
        if line.startswith("In FileSystem DMG"):
            break
        if in_dylib_block and line.startswith("/"):
            clients.append(line)
    return clients


def get_defined_exports(binary: Path, arch: str) -> set[str]:
    text = run(["nm", "-arch", arch, "-gjU", str(binary)])
    out = set()
    for line in text.splitlines():
        sym = line.strip()
        if not sym or sym.startswith("$"):
            continue
        out.add(sym)
    return out


def parse_reexport_dylib_paths(binary: Path) -> list[str]:
    text = run(["otool", "-l", str(binary)])
    out: list[str] = []
    in_reexport = False
    for raw in text.splitlines():
        line = raw.strip()
        if line == "cmd LC_REEXPORT_DYLIB":
            in_reexport = True
            continue
        if in_reexport and line.startswith("name "):
            # format: name /path/to/lib (offset XX)
            path = line.split(" ", 1)[1].split(" (offset", 1)[0].strip()
            out.append(path)
            in_reexport = False
            continue
        if line.startswith("cmd "):
            in_reexport = False
    return out


def map_built_provider_path(built_webkit: Path, system_provider_path: str) -> Path:
    # Map /System/.../Foo.framework/Foo to sibling build root Foo.framework/Foo
    # Example build root: .../WebKitBuild/Release-iphoneos
    build_root = built_webkit.parent.parent
    parts = Path(system_provider_path).parts
    if len(parts) >= 2:
        return build_root / parts[-2] / parts[-1]
    return build_root / Path(system_provider_path).name


def collect_effective_exports(
    root_binary: Path,
    arch: str,
    provider_mapper,
) -> tuple[set[str], list[str], list[str]]:
    exports: set[str] = set()
    visited: set[str] = set()
    resolved_providers: list[str] = []
    missing_providers: list[str] = []

    def walk(binary: Path) -> None:
        key = str(binary.resolve())
        if key in visited:
            return
        visited.add(key)

        exports.update(get_defined_exports(binary, arch))
        for provider in parse_reexport_dylib_paths(binary):
            provider_binary = provider_mapper(provider)
            if not provider_binary.is_file():
                missing_providers.append(provider)
                continue
            resolved_providers.append(provider)
            walk(provider_binary)

    walk(root_binary)
    # keep deterministic output
    resolved_providers = sorted(set(resolved_providers))
    missing_providers = sorted(set(missing_providers))
    return exports, resolved_providers, missing_providers


IMPORT_RE = re.compile(r"\(undefined\)\s+external\s+(\S+)\s+\(from WebKit\)$")


def get_undefined_from_webkit(binary: Path, arch: str) -> set[str]:
    text = run(["nm", "-arch", arch, "-m", "-u", str(binary)])
    out = set()
    for raw in text.splitlines():
        m = IMPORT_RE.search(raw.strip())
        if m:
            out.add(m.group(1))
    return out


def main() -> int:
    repo_root = repo_root_from_script(__file__)

    ap = argparse.ArgumentParser(
        description="Compare DSC clients' WebKit imports with built WebKit exports.",
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
    )
    ap.add_argument("--repo-root", type=Path, default=repo_root, help="Project root used for resolving default paths.")
    ap.add_argument("--dsc", required=True, type=Path, help="dyld_shared_cache_arm64e path")
    ap.add_argument(
        "--split-root",
        type=Path,
        default=None,
        help="root dir generated by `ipsw dyld split`",
    )
    ap.add_argument(
        "--build-root",
        type=Path,
        default=None,
        help="WebKitBuild/Release-iphoneos root used to infer --built-webkit when it is omitted.",
    )
    ap.add_argument(
        "--built-webkit",
        type=Path,
        default=None,
        help="Built WebKit.framework/WebKit binary. Defaults to <build-root>/WebKit.framework/WebKit.",
    )
    ap.add_argument(
        "--stock-webkit",
        type=Path,
        default=None,
        help="optional stock WebKit from split root; if omitted, auto uses split-root + system path",
    )
    ap.add_argument("--arch", default="arm64e")
    ap.add_argument(
        "--out-dir",
        type=Path,
        default=None,
        help="Directory for the generated report files.",
    )
    args = ap.parse_args()
    args.split_root = args.split_root or default_split_root(args.repo_root)
    args.build_root = args.build_root or default_release_build_root(args.repo_root)
    args.out_dir = args.out_dir or (args.repo_root / "samples" / "compare_webkit_abi")
    if args.build_root is None and args.built_webkit is None:
        ap.error("Unable to infer --build-root/--built-webkit. Pass one explicitly.")

    built_webkit = args.built_webkit or (args.build_root / "WebKit.framework/WebKit")
    if not args.dsc.is_file():
        raise SystemExit(f"DSC file does not exist: {args.dsc}")
    if not args.split_root.is_dir():
        raise SystemExit(f"Split root does not exist: {args.split_root}")
    if args.build_root is not None and not args.build_root.is_dir():
        raise SystemExit(f"Build root does not exist: {args.build_root}")
    if not built_webkit.is_file():
        raise SystemExit(f"Built WebKit binary does not exist: {built_webkit}")

    out_dir: Path = args.out_dir
    out_dir.mkdir(parents=True, exist_ok=True)

    clients = parse_clients_from_ipsw_imports(args.dsc)
    client_file_missing: list[str] = []
    required_from_clients: set[str] = set()

    for client in clients:
        f = args.split_root / client.lstrip("/")
        if not f.is_file():
            client_file_missing.append(client)
            continue
        required_from_clients |= get_undefined_from_webkit(f, args.arch)

    built_exports, built_reexports, built_reexports_missing = collect_effective_exports(
        built_webkit,
        args.arch,
        lambda provider: map_built_provider_path(built_webkit, provider),
    )

    stock_webkit = args.stock_webkit or (args.split_root / WEBKIT_PATH.lstrip("/"))
    stock_exports, stock_reexports, stock_reexports_missing = collect_effective_exports(
        stock_webkit,
        args.arch,
        lambda provider: args.split_root / provider.lstrip("/"),
    )

    missing_required_in_built = sorted(required_from_clients - built_exports)
    missing_stock_in_built = sorted(stock_exports - built_exports)
    added_in_built_vs_stock = sorted(built_exports - stock_exports)

    summary = {
        "dsc": str(args.dsc),
        "split_root": str(args.split_root),
        "built_webkit": str(built_webkit),
        "stock_webkit": str(stock_webkit),
        "arch": args.arch,
        "built_reexports": built_reexports,
        "built_reexports_missing": built_reexports_missing,
        "stock_reexports": stock_reexports,
        "stock_reexports_missing": stock_reexports_missing,
        "counts": {
            "clients_total": len(clients),
            "clients_missing_file": len(client_file_missing),
            "required_symbols_from_clients": len(required_from_clients),
            "built_exports": len(built_exports),
            "stock_exports": len(stock_exports),
            "missing_required_in_built": len(missing_required_in_built),
            "missing_stock_in_built": len(missing_stock_in_built),
            "added_in_built_vs_stock": len(added_in_built_vs_stock),
        },
        "missing_required_in_built": missing_required_in_built,
        "missing_stock_in_built": missing_stock_in_built,
        "added_in_built_vs_stock": added_in_built_vs_stock,
        "clients_missing_file": client_file_missing,
    }

    (out_dir / "summary.json").write_text(
        json.dumps(summary, ensure_ascii=False, indent=2) + "\n", encoding="utf-8"
    )
    (out_dir / "clients.txt").write_text("\n".join(clients) + "\n", encoding="utf-8")
    (out_dir / "required_from_clients.txt").write_text(
        "\n".join(sorted(required_from_clients)) + "\n", encoding="utf-8"
    )
    (out_dir / "built_exports.txt").write_text(
        "\n".join(sorted(built_exports)) + "\n", encoding="utf-8"
    )
    (out_dir / "stock_exports.txt").write_text(
        "\n".join(sorted(stock_exports)) + "\n", encoding="utf-8"
    )

    print(json.dumps(summary["counts"], ensure_ascii=False, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
